export const BRAND = {
  name: 'Emaro Premium Auto Care',
  shortName: 'Emaro',
  tagline: 'więcej niż czyste auto',
  phone: '+48 577 123 029',
  email: 'emaroautocare@gmail.com',
  whatsapp: 'https://wa.me/48577123029',
  telegram: 'https://t.me/emaro_premium',
  address: 'Warszawa i okolice',
  city: 'Warszawa, Polska',
  instagram: 'https://www.instagram.com/emaro.premium/',
  logo: '/images/emaro/logo.png',
  heroDesktop: '/images/emaro/hero-desktop.png',
  heroMobile: '/images/emaro/hero-mobile.png',
  contactImage: '/images/emaro/hero-desktop.png',
} as const
